mirrors:
  sources:
    fetch:
      url: file:///g/data/ik11/spack/0.20.1/sources
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///g/data/ik11/spack/0.20.1/sources
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
